name: BlackAuction
version: '1.0'
main: me.korolkotov.blackauction.Main
api-version: '1.21'
author: KoroLKotov

softdepend: [Vault, CoinsEngine]

commands:
  blackauction:
    aliases: [ba]
    description: 'Основная команда плагина BlackAuction.'